/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FileTimestamp } from "./FileTimestamp";
export * as factories from "./factories";
export { FileTimestamp__factory } from "./factories/FileTimestamp__factory";
